Update patch set 2
Patch Set 2: Code-Review+1 Verified-1

[INFO]  Current directory changed to: '/home/michal/DEV/nfengine/Bin/x86_64/Release/../../..'
[INFO]  49 visuals found
[INFO]  Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' compilation output:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: 0:16: error(#143) Undeclared identifier: gl_Position
ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR] Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' failed to compile.
[INFO]  Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' compilation output:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: 0:16: error(#143) Undeclared identifier: gl_Position
ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR] Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' failed to compile.
[INFO]  Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' compilation output:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: 0:16: error(#143) Undeclared identifier: gl_Position
ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR] Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' failed to compile.
[INFO]  Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' compilation output:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: 0:16: error(#143) Undeclared identifier: gl_Position
ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR] Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' failed to compile.
[INFO]  Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' compilation output:
Vertex shader(s) failed to link.
Vertex link error: INVALID_OPERATION.
ERROR: 0:16: error(#143) Undeclared identifier: gl_Position
ERROR: error(#273) 1 compilation errors.  No code generated


[ERROR] Shader 'nfEngine/nfRendererDemo/Shaders/OGL4/TestVS.glsl' failed to compile.


Same errors on Windows

Patch-set: 2
Label: Verified=-1