Update patch set 16
Patch Set 16: Verified-1

On GCC 4.8.4 (Ubuntu 14.04):

nfEngine/nfCommonTest/../nfCommon/Library.hpp: In instantiation of ‘bool NFE::Common::Library::GetSymbol(const string&, T&) [with T = int (*)(int, int); std::string = std::basic_string<char>]’:
nfEngine/nfCommonTest/LibraryTest.cpp:34:5:   required from here
nfEngine/nfCommonTest/../nfCommon/Library.hpp:69:16: error: ISO C++ forbids casting between pointer-to-function and pointer-to-object [-Werror=pedantic]

Patch-set: 16