Update patch set 10
Patch Set 10: Verified-1

While compiling nfRenderer:
2>RendererResources.cpp(783): error C2440: '=' : cannot convert from 'void *' to 'HWND'
2>          Conversion from 'void*' to pointer to non-'void' requires an explicit cast

While compiling nfRendererTest and nfEngineTest:
3>main.cpp(75): error C2664: 'void NFE::Common::Window::SetTitle(const char *)' : cannot convert argument 1 from 'const wchar_t [23]' to 'const char *'
3>          Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast

Patch-set: 10
Label: Verified=-1