Update patch set 1
Patch Set 1: Verified-1

Does not build with -DSANITIZE=thread

[ 44%] Building CXX object nfEngine/nfCommonTest/CMakeFiles/nfCommonTest.dir/AlignedTest.cpp.o
In file included from /home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/AlignedTest.cpp:8:0:
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp: In instantiation of ‘static void* NFE::Common::Aligned<Alignment>::operator new(size_t) [with long unsigned int Alignment = 16ul; size_t = long unsigned int]’:
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/AlignedTest.cpp:33:51:   required from here
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp:48:16: error: ‘operator new’ must not return NULL unless it is declared ‘throw()’ (or -fcheck-new is in effect) [-Werror]
         return nullptr;
                ^
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp: In instantiation of ‘static void* NFE::Common::Aligned<Alignment>::operator new(size_t) [with long unsigned int Alignment = 64ul; size_t = long unsigned int]’:
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/AlignedTest.cpp:34:51:   required from here
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp:48:16: error: ‘operator new’ must not return NULL unless it is declared ‘throw()’ (or -fcheck-new is in effect) [-Werror]
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp: In instantiation of ‘static void* NFE::Common::Aligned<Alignment>::operator new(size_t) [with long unsigned int Alignment = 4096ul; size_t = long unsigned int]’:
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/AlignedTest.cpp:35:55:   required from here
/home/lkostyra/qt_workspaces/code/nfengine/nfEngine/nfCommonTest/../nfCommon/Aligned.hpp:48:16: error: ‘operator new’ must not return NULL unless it is declared ‘throw()’ (or -fcheck-new is in effect) [-Werror]

Ubuntu 14.04.4, GCC 4.9.3

Patch-set: 1
Label: Verified=-1