Fix for GCC 5.1.1
Builing the project with newest version of GCC failed with error:
"nfCommonTest/Test.hpp:12:14: error: ‘TEXTSIZE’ defined but not used".
TEXSIZE and other constants definitions have been moved to separate cpp file.

Verification:
    Rebuild all, run tests.

Change-Id: Ibe2d150b72409856aba15537b1cbac6e2d12e997