Update patch set 19
Patch Set 19: Verified-1

Fails on Windows:

====Running nfCommonTest for Win32\Release
Note: Google Test filter = SystemInfoTest.MemoryInfoTest
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from SystemInfoTest
[ RUN      ] SystemInfoTest.MemoryInfoTest
SystemInfoTest.cpp(21): error: Expected: (sysInfoPtr->GetMemTotalSwapKb()) < (1000000000), actual: 18446744073709549764 vs 1000000000
[  FAILED  ] SystemInfoTest.MemoryInfoTest (1000 ms)
[----------] 1 test from SystemInfoTest (1000 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1000 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SystemInfoTest.MemoryInfoTest

If that helps - I have Pagefile turned off on my Windows PC. Maybe this is the reason, something is incorrectly calculated and the variables keeping total swap amount are underflowed.

Patch-set: 19
Label: Verified=-1