Update patch set 6
Patch Set 6:

On Windows:

Repeating all tests (iteration 120) . . .

Note: Google Test filter = FileAsync*
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from FileAsyncTest
[ RUN      ] FileAsyncTest.Constructors
6.4221 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './some/path': The system cannot find the path specified.

6.4234 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './some/path': The system cannot find the path specified.

6.4240 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './some/path': The system cannot find the path specified.

6.4246 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[       OK ] FileAsyncTest.Constructors (3 ms)
[ RUN      ] FileAsyncTest.Read
6.4260 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\file.cpp:88: Failed to open file './testFile.async': The process cannot access the file because it is being used by another process.

f:\nfengine\nfengine\nfcommontest\fileasynctest.cpp(120): error: Value of: testFile.IsOpened()
  Actual: false
Expected: true
6.4271 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[  FAILED  ] FileAsyncTest.Read (2 ms)
[ RUN      ] FileAsyncTest.Write
6.4291 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './testFile.async': The process cannot access the file because it is being used by another process.

f:\nfengine\nfengine\nfcommontest\fileasynctest.cpp(168): error: Value of: testAsyncFile.IsOpened()
  Actual: false
Expected: true
6.4333 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[  FAILED  ] FileAsyncTest.Write (7 ms)
[ RUN      ] FileAsyncTest.OpenClose
6.4367 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './testFile.async': The process cannot access the file because it is being used by another process.

f:\nfengine\nfengine\nfcommontest\fileasynctest.cpp(211): error: Value of: testAsyncFile.IsOpened()
  Actual: false
Expected: true
6.4377 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[  FAILED  ] FileAsyncTest.OpenClose (2 ms)
[ RUN      ] FileAsyncTest.OperationsOnClosed
6.4395 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './testFile.async': The process cannot access the file because it is being used by another process.

f:\nfengine\nfengine\nfcommontest\fileasynctest.cpp(231): error: Value of: testAsyncFile.IsOpened()
  Actual: false
Expected: true
6.4406 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[  FAILED  ] FileAsyncTest.OperationsOnClosed (1 ms)
[ RUN      ] FileAsyncTest.InvalidOperations
6.4454 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\fileasyncplatform.cpp:121: Failed to open file './testFile.async': The process cannot access the file because it is being used by another process.

f:\nfengine\nfengine\nfcommontest\fileasynctest.cpp(250): error: Value of: testAsyncFile.IsOpened()
  Actual: false
Expected: true
6.4468 [ERROR  ] f:\nfengine\nfengine\nfcommon\win\filesystem.cpp:227: Failed to delete file './testFile.async': The process cannot access the file because it is being used by another process.

[  FAILED  ] FileAsyncTest.InvalidOperations (3 ms)
[----------] 6 tests from FileAsyncTest (28 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (33 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] FileAsyncTest.Read
[  FAILED  ] FileAsyncTest.Write
[  FAILED  ] FileAsyncTest.OpenClose
[  FAILED  ] FileAsyncTest.OperationsOnClosed
[  FAILED  ] FileAsyncTest.InvalidOperations

Patch-set: 6