Update patch set 5
Patch Set 5: Code-Review-1 Verified-1

(2 comments)

Does not compile on Linux - ifdefs are missing in Memory.hpp

/home/user/nfengine/nfEngine/nfCommon/Memory.cpp: In function ‘NFE::Common::uint32 NFE::Common::MemoryCheck(const void*, size_t)’:
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:16:5: error: ‘MEMORY_BASIC_INFORMATION’ was not declared in this scope
     MEMORY_BASIC_INFORMATION info;
     ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:16:30: error: expected ‘;’ before ‘info’
     MEMORY_BASIC_INFORMATION info;
                              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:17:24: error: ‘info’ was not declared in this scope
     VirtualQuery(ptr, &info, sizeof(info));
                        ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:17:42: error: ‘VirtualQuery’ was not declared in this scope
     VirtualQuery(ptr, &info, sizeof(info));
                                          ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:22:5: error: ‘UINT’ was not declared in this scope
     UINT flags = 0;
     ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:22:10: error: expected ‘;’ before ‘flags’
     UINT flags = 0;
          ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:25:14: error: ‘PAGE_EXECUTE_READ’ was not declared in this scope
         case PAGE_EXECUTE_READ:
              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:26:13: error: ‘flags’ was not declared in this scope
             flags = ACCESS_READ | ACCESS_EXECUTE;
             ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:29:14: error: ‘PAGE_EXECUTE’ was not declared in this scope
         case PAGE_EXECUTE:
              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:33:14: error: ‘PAGE_EXECUTE_READWRITE’ was not declared in this scope
         case PAGE_EXECUTE_READWRITE:
              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:37:14: error: ‘PAGE_READONLY’ was not declared in this scope
         case PAGE_READONLY:
              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:41:14: error: ‘PAGE_READWRITE’ was not declared in this scope
         case PAGE_READWRITE:
              ^
/home/user/nfengine/nfEngine/nfCommon/Memory.cpp:46:12: error: ‘flags’ was not declared in this scope
     return flags;
            ^
make[2]: *** [nfEngine/nfCommon/CMakeFiles/nfCommon.dir/Memory.cpp.o] Błąd 1
make[2]: *** Oczekiwanie na niezakończone zadania....
make[1]: *** [nfEngine/nfCommon/CMakeFiles/nfCommon.dir/all] Błąd 2
make: *** [all] Błąd 2

Patch-set: 5
Label: Code-Review=-1
Label: Verified=-1